[font]
normal = { family = "CaskaydiaMono Nerd Font" }
bold = { family = "CaskaydiaMono Nerd Font" }
italic = { family = "CaskaydiaMono Nerd Font" }
size = 11

[window]
padding.x = 4
padding.y = 4
decorations = "None"
opacity = 0.4
